services:

  app:
    image: bookstore/app
    container_name: book_store_app
    build:
      context: ./
    networks:
      - app_network
    ports:
      - 8080:8080
    environment:
      SPRING_CONFIG_LOCATION: "src/main/resources/application-prod.yaml"
        #    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    volumes:
      - ./book_store/src/main/resources/:/app/src/main/resources

  postgres:
    image: bookstore/postgres
    container_name: book_store_postgres
    build:
      context: ./postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - app_network
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: book_store_keycloak
    command: start-dev
    ports:
      - 8082:8080
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://book_store_postgres:5433/book_store_keycloak"
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_USER: admin
      KC_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - app_network
    restart: no
    depends_on:
      postgres:
        condition: service_healthy

networks:
  app_network:
    driver: bridge

volumes:
  postgres:
    driver: local
  book_store_resources:
