services:
  postgres-keycloak:
    image: postgres:15.4
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: book-store-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - keycloak-network
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev
    ports:
      - 8082:8080
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_DATABASE: book-store-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_USER: admin
      KC_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - keycloak-network
    restart: unless-stopped
    depends_on:
      postgres-keycloak:
        condition: service_healthy

networks:
  keycloak-network:
    driver: bridge
volumes:
  keycloak-postgres:
