server:
  servlet:
    context-path: /app
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:~/book_store;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    enabled: false
  jpa:
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      search:
        enabled: true
        default:
          indexmanager: elasticsearch
          elasticsearch:
            host: http://localhost:9200
      jakarta:
        persistence:
          sharedCache:
            mode: ALL